name: Build

on:
    workflow_call:

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up
              uses: ./.github/actions/setup
            - name: Build extension and tests
              run: pnpm run build --env production
            - name: Save built extension assets to cache
              uses: actions/cache/save@v3
              with:
                  path: ./out
                  key: 'build-${{ github.sha }}'
