name: Package

on:
    workflow_call:

jobs:
    package-linux-x64:
        name: Package
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up
              uses: ./.github/actions/setup
            - name: Retrieve Linux build
              uses: actions/cache/restore@v3
              with:
                  path: ./out
                  key: 'build-${{ github.sha }}'
            - name: Package extension
              run: pnpm run package
            - name: Cache package
              uses: actions/cache/save@v3
              with:
                  path: '*.vsix'
                  key: 'package-${{ github.sha }}'
