name: Test

on:
    workflow_call:

jobs:
    test-linux-x64:
        name: Test on Linux (x64)
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: ['stable']
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up
              uses: ./.github/actions/setup
            - name: Restore Linux x64 build
              uses: actions/cache/restore@v3
              with:
                  path: ./out
                  key: 'linux-x64-build-${{ github.sha }}'
            - name: Run tests
              run: |
                  xvfb-run -a node ./out/test-script.js --env node --version "${{ matrix.version }}"
    test-macos-x64:
        name: Test on macOS (x64)
        runs-on: macos-latest
        strategy:
            matrix:
                version: ['stable']
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up
              uses: ./.github/actions/setup
            - name: Restore macOS x64 build
              uses: actions/cache/restore@v3
              with:
                  path: ./out
                  key: 'macos-x64-build-${{ github.sha }}'
            - name: Run tests
              run: |
                  node ./out/test-script.js --env node --version "${{ matrix.version }}"
    test-windows-x64:
        name: Test on Windows (x64)
        runs-on: windows-latest
        strategy:
            matrix:
                version: ['stable']
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up
              uses: ./.github/actions/setup
            - name: Restore Windows x64 build
              uses: actions/cache/restore@v3
              with:
                  path: ./out
                  key: 'windows-x64-build-${{ github.sha }}'
            - name: Run tests
              run: |
                  node ./out/test-script.js --env node --version "${{ matrix.version }}"
    test-universal:
        name: Test in browser (universal)
        runs-on: ubuntu-latest
        strategy:
            matrix:
                version: ['stable']
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Set up
              uses: ./.github/actions/setup
            - name: Install playwright browsers
              run: pnpm dlx playwright install chromium --with-deps
            - name: Restore Universal build
              uses: actions/cache/restore@v3
              with:
                  path: ./out
                  key: 'universal-build-${{ github.sha }}'
            - name: Run tests
              run: |
                  node ./out/test-script.js --env web --version "${{ matrix.version }}"
