name: Integrate

on:
  push:
    tags-ignore: ["*"]
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  rome:
    name: Rome
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up
        uses: ./.github/actions/setup
      - name: Run Rome
        run: pnpm dlx rome ci

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up
        uses: ./.github/actions/setup
      - name: Build extension
        run: pnpm run build
      - name: Save built extension assets to cache
        uses: actions/cache/save@v3
        with:
          path: ./out
          key: "build-${{ github.sha }}"
