name: Release

on:
  push:
    branches: ["main"]

jobs:
  integrate:
    name: Integrate
    uses: ./.github/workflows/integrate.yaml

  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up
        uses: ./.github/actions/setup
      - name: Retrieve Linux build
        uses: actions/cache/restore@v3
        with:
          path: ./out
          key: "build-${{ github.sha }}"
      - name: Package extension
        run: pnpm run package
      - name: Cache package
        uses: actions/cache/save@v3
        with:
          path: "*.vsix"
          key: "package-${{ github.sha }}"

  release:
    name: Release
    needs: ["integrate"]
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release.outputs.tag_name }}
      release_created: ${{ steps.release.outputs.release_created }}
      version:
        "${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor
        }}.${{ steps.release.outputs.patch }}"
    steps:
      - id: release
        name: Run release-please
        uses: google-github-actions/release-please-action@v3.7.1
        with:
          release-type: node
          pull-request-header: "Upcoming version of the VS Code extension"
          package-name: inertia

  publish:
    name: Publish
    needs: ["release", "package"]
    uses: ./.github/workflows/publish.yaml
    secrets: inherit
    with:
      tag_name: ${{ needs.release.outputs.tag_name }}
      version: ${{ needs.release.outputs.version }}
